{% set name = "gladier-tools" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: da177f5e33bbdb9db65251eb0c49b8ea24cfb813865622364ab7a3148320c043

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - gladier >=0.9.0
    - python >={{ python_min }}

test:
  imports:
    - gladier_tools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/globus-gladier/gladier-tools
  summary: A set of reusable Gladier Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
