{% set name = "gladier-tools" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 1f554533d4b34b06e1178c400ac3d0358b21d162ebb3e1e8dea4a8f25371e008

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - gladier >=0.9.0
    - python >={{ python_min }}

test:
  imports:
    - gladier_tools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/globus-gladier/gladier-tools
  summary: A set of reusable Gladier Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
