{% set name = "gladier-tools" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gladier-tools-{{ version }}.tar.gz
    sha256: c2b39ac7f0a5ff0ff52dcac8cfd63c21162105216b48a243270ec95a61b2a869
    # FIXME: Remove requirements.txt for next release; missing in PYPI sdist
  - url: https://raw.githubusercontent.com/globus-gladier/gladier-tools/v0.4.0/requirements.txt
    sha256: 9b0cd22144d3eb87633580b86ad6ff6f77467a1123d8711a45a578149e173e69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - gladier >=0.6.3
    - python >=3.6

test:
  imports:
    - gladier_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/globus-gladier/gladier-tools
  summary: A set of reusable Gladier Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
