{% set name = "gladier-tools" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gladier-tools-{{ version }}.tar.gz
    sha256: a162ee7aae7b86eef1cbe05046c2d95d0bd154b5d67bfbb8593c50f882bd8451

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - gladier >=0.9.0
    - python >=3.6

test:
  imports:
    - gladier_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/globus-gladier/gladier-tools
  summary: A set of reusable Gladier Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
